# mongodb service
version: '3.1'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongodb_storage:/data/db
    restart: always
    ports:
      - 127.0.0.1:12346:27017
      - 10.0.2.15:12346:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ansible
      MONGO_INITDB_ROOT_PASSWORD: ansible
    networks:
      - inside
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ansible
      ME_CONFIG_MONGODB_ADMINPASSWORD: ansible
      ME_CONFIG_MONGODB_URL: mongodb://ansible:ansible@mongodb:27017/
    networks:
      - inside 
volumes:
    mongodb_storage: {}

networks:
    inside:
      name: mongodb_network