---
- name: Install docker
  hosts: server1
  become: true
  vars_files:
    - vars.yaml

  tasks:
    - name: Add docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: absent

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: absent
        update_cache: true
      loop: "{{ requried_packages }}"

    - name: Autmove
      apt:
        autoremove: true
